# Generated by Django 6.0.5 on 2026-05-05 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(default='FEDERAL TEACHING HOSPITAL KATSINA', max_length=200)),
                ('department_name', models.CharField(default='PHARMACY DEPARTMENT', max_length=200)),
                ('unit_name', models.CharField(default='ACCIDENT AND EMERGENCY PHARMACY UNIT', max_length=200)),
            ],
            options={
                'ordering': ['department_name'],
            },
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roster_title', models.CharField(default="PHARMACISTS' CALL DUTY ROSTER", max_length=200)),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('year', models.IntegerField()),
                ('num_slots', models.IntegerField(choices=[(1, '1 Slot'), (2, '2 Slots'), (3, '3 Slots')], default=3)),
                ('slot1_label', models.CharField(default='FIRST ON CALL', max_length=100)),
                ('slot2_label', models.CharField(default='SECOND ON CALL', max_length=100)),
                ('slot3_label', models.CharField(default='THIRD ON CALL', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rosters', to='roster.department')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('department', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='PHARM.', max_length=50)),
                ('name', models.CharField(help_text='Full name e.g. IBRAHIM ABUKUR', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='roster.department')),
            ],
            options={
                'verbose_name_plural': 'Staff',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RosterEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='roster.roster')),
                ('slot1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot1_entries', to='roster.staff')),
                ('slot2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot2_entries', to='roster.staff')),
                ('slot3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot3_entries', to='roster.staff')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('roster', 'date')},
            },
        ),
    ]
