# Generated by Django 6.0.5 on 2026-05-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0004_staff_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roster',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], db_index=True),
        ),
        migrations.AlterField(
            model_name='roster',
            name='year',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='rosterentry',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='staffavailability',
            name='end_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='staffavailability',
            name='start_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='roster',
            index=models.Index(fields=['unit', 'month', 'year'], name='roster_rost_unit_id_16a3a7_idx'),
        ),
        migrations.AddIndex(
            model_name='rosterentry',
            index=models.Index(fields=['roster', 'date'], name='roster_rost_roster__c4c04e_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['unit', 'is_active'], name='roster_staf_unit_id_e99bb4_idx'),
        ),
        migrations.AddIndex(
            model_name='staffavailability',
            index=models.Index(fields=['staff_id', 'start_date', 'end_date'], name='roster_staf_staff_i_ff8ea9_idx'),
        ),
    ]
