# Generated by Django 6.0.5 on 2026-05-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0005_add_db_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='roster',
            name='roster_type',
            field=models.CharField(choices=[('CALL', 'Call Duty Roster'), ('PTECH', 'PTech Shift Roster')], db_index=True, default='CALL', max_length=10),
        ),
        migrations.AddField(
            model_name='roster',
            name='shift_config',
            field=models.CharField(blank=True, choices=[('MA_N', 'Morning, Afternoon, Night'), ('MAN_N', 'Morning-Afternoon, Night'), ('MA_NN', 'Morning, Afternoon-Night'), ('MAN_NN', 'Morning-Afternoon-Night')], help_text='Required for PTech rosters', max_length=10, null=True),
        ),
    ]
