# Generated by Django 6.0.5 on 2026-05-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0008_staff_type'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ptechstaffentry',
            new_name='roster_ptec_roster__bb9fa1_idx',
            old_name='roster_ptec_roster__date_idx',
        ),
        migrations.RenameIndex(
            model_name='ptechstaffentry',
            new_name='roster_ptec_roster__7e34d6_idx',
            old_name='roster_ptec_roster__staff_idx',
        ),
        migrations.RenameIndex(
            model_name='staff',
            new_name='roster_staf_unit_id_e5b796_idx',
            old_name='roster_staf_unit_stype_idx',
        ),
        migrations.AddField(
            model_name='staff',
            name='phone_number',
            field=models.CharField(blank=True, help_text='e.g. 08012345678', max_length=20),
        ),
        migrations.AlterField(
            model_name='ptechstaffentry',
            name='shift',
            field=models.CharField(choices=[('M', 'Morning'), ('A', 'Afternoon'), ('N', 'Night'), ('O', 'Off'), ('CM', 'Combined Morning'), ('L', 'Leave')], max_length=2),
        ),
    ]
