# Generated by Django 6.0.5 on 2026-05-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0009_staff_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roster',
            name='roster_type',
            field=models.CharField(choices=[('CALL', 'Call Duty Roster'), ('PTECH', 'PTech Shift Roster'), ('PHARM_SHIFT', 'Pharmacist Shift Roster')], db_index=True, default='CALL', max_length=11),
        ),
    ]
