# Generated by Django 6.0.5 on 2026-05-08 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0011_activitylog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-timestamp'], 'permissions': [('can_view_activity_log', 'Can view activity log')]},
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='roster_acti_timesta_b0fa44_idx',
            old_name='roster_acti_timesta_idx',
        ),
    ]
