# Generated by Django 6.0.5 on 2026-05-08 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0012_activitylog_view_permission'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('hospital', 'department_name')},
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('department', 'unit_name')},
        ),
    ]
